[workspace]
members = ["evo-grid", "evo-grid-pixels"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Franz Amador <franzamador@gmail.com>"]

[workspace.dependencies]
rand = "0.9"
