[package]
name = "pixels-problem"
version.workspace = true
edition.workspace = true
authors.workspace = true

[features]
optimize = ["log/release_max_level_warn"]
default = ["optimize"]

[dependencies]
log = "0.4"
pixels = "0.15"
winit = { version = "0.30", features = ["rwh_05"] }
