[package]
name = "evo-grid-pixels"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
evo-grid = { path = "../evo-grid" }
pixels-main-support = { path = "../pixels-main-support" }
world-grid = { path = "../world-grid" }
