[package]
name = "conway-life-pixels"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
pixels-main-support = { path = "../pixels-main-support" }
world-grid = { path = "../world-grid" }
